config/routes.rb
TennisCourtBookingApp::Application.routes.draw do
  root 'tennis_courts#index'

  resources :tennis_courts do
	  resources :bookings
	end

  

end

app/models/booking.rb
require_relative './concerns/bookable'

class Booking < ActiveRecord::Base
  include Bookable
end

app/models/concerns/bookable.rb
module Bookable
  extend ActiveSupport::Concern

  included do
    belongs_to :tennis_court

    validates :start_time, presence: true 
    validates :length, presence: true, numericality: { greater_than: 0 }
    validate :start_date_cannot_be_in_the_past
    validate :overlaps

    before_validation :calculate_end_time
  

    scope :end_during, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('end_time > ? AND end_time < ?', new_start_time, new_end_time)
      else
        return nil
      end
    end

    scope :start_during, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time > ? AND start_time < ?', new_start_time, new_end_time)
      else
        return nil
      end
    end

    scope :happening_during, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time > ? AND end_time < ?', new_start_time, new_end_time)
      else
        return nil
      end 
    end

    scope :enveloping, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time < ? AND end_time > ?', new_start_time, new_end_time)
      else
        return nil
      end
    end

    scope :identical, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time = ? AND end_time = ?', new_start_time, new_end_time)
      else
        return nil
      end
    end
  end

  def overlaps
    overlapping_bookings = [ 
      tennis_court.bookings.end_during(start_time, end_time),
      tennis_court.bookings.start_during(start_time, end_time),
      tennis_court.bookings.happening_during(start_time, end_time),
      tennis_court.bookings.enveloping(start_time, end_time),
      tennis_court.bookings.identical(start_time, end_time)
    ].flatten

    overlapping_bookings.delete self
    if overlapping_bookings.any?
      errors.add(:base, 'Slot has already been booked')
    end
  end

  def start_date_cannot_be_in_the_past
    if start_time && start_time < DateTime.now + (15.minutes)
      errors.add(:start_time, 'must be at least 15 minutes from present time')
    end
  end

  def calculate_end_time
    start_time = validate_start_time
    length = validate_length
    if start_time && length
      self.end_time = start_time + (length.hours - 60)
    end
  end


  def as_json(options = {})  
   {  
    :id => self.id,  
    :start => self.start_time,  
    :end => self.end_time + 60,  
    :recurring => false, 
    :allDay => false
   }  
  end  

  private

    def validate_start_time
      if !self.start_time.nil?
        start_time = self.start_time
      else
        return nil
      end
    end

    def validate_length
      if !self.length.nil?
        length = self.length.to_i
      else
        return nil
      end
    end

end

app/models/tennis_court.rb
class TennisCourt < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  respond_to :html, :xml, :json
  
  before_action :find_tennis_court

  def index
    @bookings = Booking.where("tennis_court_id = ? AND end_time >= ?", @tennis_court.id, Time.now).order(:start_time)
    respond_with @bookings
  end

  def new
    @booking = Booking.new(tennis_court_id: @tennis_court.id)
  end

  def create
    @booking =  Booking.new(params[:booking].permit(:tennis_court_id, :start_time, :length))
    @booking.tennis_court = @tennis_court
    if @booking.save
      redirect_to tennis_court_bookings_path(@tennis_court, method: :get)
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id]).destroy
    if @booking.destroy
      flash[:notice] = "Booking: #{@booking.start_time.strftime('%e %b %Y %H:%M%p')} to #{@booking.end_time.strftime('%e %b %Y %H:%M%p')} deleted"
      redirect_to tennis_court_bookings_path(@tennis_court)
    else
      render 'index'
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    # @booking.tennis_courts = @tennis_courts

    if @booking.update(params[:booking].permit(:tennis_court_id, :start_time, :length))
      flash[:notice] = 'Your booking was updated succesfully'

      if request.xhr?
        render json: {status: :success}.to_json
      else
        redirect_to tennis_court_bookings_path(@tennis_court)
      end
    else
      render 'edit'
    end
  end

  private

  def save booking
    if @booking.save
        flash[:notice] = 'booking added'
        redirect_to tennis_court_booking_path(@tennis_court, @booking)
      else
        render 'new'
      end
  end

  def find_tennis_court
    if params[:tennis_court_id]
      @tennis_court = TennisCourt.find_by_id(params[:tennis_court_id])
    end
  end

end

app/controllers/tennis_courts_controller.rb
class TennisCourtsController < ApplicationController

  def index
    @tennis_courts = TennisCourt.all
  end

  def new
    @tennis_court = TennisCourt.new
  end

  def create
    @tennis_court = TennisCourt.create(tennis_court_params)
    if @tennis_court.save
      name = @tennis_court.name
      redirect_to tennis_courts_path
      flash[:notice] = "#{name} created"
    else
      render 'new'
      flash[:error] = "Unable to create tennis court. Please try again"
    end
  end

  def destroy
    @tennis_court = TennisCourt.find(params[:id])
    @tennis_court.destroy
    redirect_to tennis_courts_path
  end

  def edit
    @tennis_court = TennisCourt.find(params[:id])
  end

  def update
    @tennis_court = TennisCourt.find(params[:id])
    @tennis_court.update tennis_court_params
    if @tennis_court.save
      flash[:notice] = "Your tennis court was updated succesfully"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

    def tennis_court_params
      params.require(:tennis_court).permit(:name, :delete)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_errors.html.erb
<% if @booking.errors.any? %>
  <div class="errors">
    <h3><%= pluralize(@booking.errors.count, 'error') %>
      prohibited this booking from being saved:
    </h3>
    <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/bookings/_form.html.erb
<%= form_for([@tennis_court, @booking]) do |f| %>
  <p>
    <%= f.label 'start_time', 'Start time' %>
    <%= f.datetime_select :start_time, { minute_step: 15 } %>
  </p>
  <p>
    <%= f.label 'length', 'Length of booking in hours' %>
    <%= f.number_field 'length', min: 1 %>
  </p>
  <%= f.submit 'Submit' %>
<% end %> 

app/views/bookings/edit.html.erb
<h3>Edit booking for <%= @tennis_court.name %></h3>

<%= render 'errors' %>
<%= render 'form' %>

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>

app/views/bookings/index.html.erb
<h3> Bookings for 
  <%= select_tag :court,
      options_for_select(TennisCourt.all.map {|c| [ c.name, tennis_court_bookings_path(c) ]}, tennis_court_bookings_path(@tennis_court))
  %>
</h3>

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>
<table>
  <tr>
    <th>Start</th>
    <th>End</th>
  </tr>
  
  <% @bookings.each do |booking| %>
  <tr>
    <td>
      <%= booking.start_time.strftime('%e %b %Y %H:%M%p') %>
    </td>
    <td>
      <%= (booking.calculate_end_time + 60).strftime('%e %b %Y %H:%M%p') %>
    </td>
    <td><%= link_to "Delete", tennis_court_booking_path(@tennis_court, booking), data: { confirm: 'Are you sure?' }, method: :delete %>
    </td>
    <td><%= link_to "Edit", edit_tennis_court_booking_path(@tennis_court, booking) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/bookings/new.html.erb
<h3>Add booking for <%= @tennis_court.name %></h3>
  
<%= render 'errors' %>
<%= render 'form' %> 

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>

app/views/bookings/show.html.erb
<h3>Booking Confirmation</h3>
<p>Your booking is confirmed for
  <%= @tennis_court.name %>
  ':'
  <%= @booking.start_time.strftime('%e %b %Y %H:%M%p') %>
  until
  <%= (@booking.calculate_end_time + 60)strftime('%e %b %Y %H:%M%p') %>

app/views/layouts/_flash.html.haml
= flash[:notice]
= flash[:alert]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TennisCourtBookingApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="wrapper">
		<%= yield %>
	</div>
</body>
</html>

app/views/tennis_courts/_errors.html.erb
<% if @tennis_court.errors.any? %>
  <div class="errors">
    <h3>
      <%= pluralize(@tennis_court.errors.count, 'error') %>
      prohibited this tennis_court from being saved:
    </h3>
    <ul>
      <% @tennis_court.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tennis_courts/_form.html.erb
<%= form_for @tennis_court do |f| %>
  <%= render 'errors' %>
  <%= f.label 'name', 'Name' %>
  <%= f.text_field 'name', placeholder: 'Name'%>
  <%= f.submit 'Submit' %>
<% end %>

app/views/tennis_courts/edit.html.erb
<%= render 'form' %>

app/views/tennis_courts/index.html.erb
<h3>tennis courts</h3>

<% @tennis_courts.each do |tennis_court| %>
  <div class="tennis_court">
    <%= tennis_court.name %>
    <%= link_to "Show all bookings", tennis_court_bookings_path(tennis_court) %>
    <%= link_to "Delete", tennis_court_path(tennis_court), data: { confirm: 'Are you sure?' }, method: :delete %>
    <%= link_to "Edit", edit_tennis_court_path(tennis_court) %>
    <%= link_to "Add booking", new_tennis_court_booking_path(tennis_court) %>
  </div>
<% end %>

app/views/tennis_courts/new.html.erb
<%= render 'form' %>